# Import `Packages`

In [2]:
import pandas as pd
import os

### Read all files and concat them in 1 file

In [3]:
path = r'C:\SalesAnalysis\Dataset'
files = [file for file in os.listdir(path) if not file.startswith('.')] # Ignore hidden files

all_months_data = pd.DataFrame()

for file in files:
    current_data = pd.read_csv(path+"/"+file)
    all_months_data = pd.concat([all_months_data, current_data])
    
all_months_data.to_csv("data.csv", index=False)

In [4]:
df1 = pd.read_csv("data.csv")

#create a copy of the df
df = df1.copy()
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

### `Clean` the data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

In [6]:
df.isna().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df.isna().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [9]:
unique_values = {column: df[column].unique() for column in df.columns}
unique_values

{'Order ID': array(['176558', '176559', '176560', ..., '259355', '259356', '259357'],
       shape=(178438,), dtype=object),
 'Product': array(['USB-C Charging Cable', 'Bose SoundSport Headphones',
        'Google Phone', 'Wired Headphones', 'Macbook Pro Laptop',
        'Lightning Charging Cable', '27in 4K Gaming Monitor',
        'AA Batteries (4-pack)', 'Apple Airpods Headphones',
        'AAA Batteries (4-pack)', 'iPhone', 'Flatscreen TV',
        '27in FHD Monitor', '20in Monitor', 'LG Dryer', 'ThinkPad Laptop',
        'Vareebadd Phone', 'LG Washing Machine', '34in Ultrawide Monitor',
        'Product'], dtype=object),
 'Quantity Ordered': array(['2', '1', '3', '5', 'Quantity Ordered', '4', '7', '6', '8', '9'],
       dtype=object),
 'Price Each': array(['11.95', '99.99', '600', '11.99', '1700', '14.95', '389.99',
        '3.84', '150', '2.99', '700', '300', '149.99', '109.99', '600.0',
        '999.99', '400', '379.99', 'Price Each', '700.0', '1700.0',
        '150.0', '300.0', '400.0'], dtype=object),
 'Order Date': array(['04/19/19 08:46', '04/07/19 22:30', '04/12/19 14:38', ...,
        '09/23/19 07:39', '09/19/19 17:30', '09/30/19 00:18'],
       shape=(142396,), dtype=object),
 'Purchase Address': array(['917 1st St, Dallas, TX 75001',
        '682 Chestnut St, Boston, MA 02215',
        '669 Spruce St, Los Angeles, CA 90001', ...,
        '981 4th St, New York City, NY 10001',
        '840 Highland St, Los Angeles, CA 90001',
        '220 12th St, San Francisco, CA 94016'],
       shape=(140788,), dtype=object)}

### information about the concatenat the CSV files

When concatenating multiple CSV files, it's possible that the headers from all the files get mixed with our data.

In this case, we are checking the `Price Each` and `Quantity Ordered` column because this columns normaly have only numeric value

In [10]:
alpha_values = set()

# Iterate through the 'Order Date' column
for value in df['Price Each']:
    if any(char.isalpha() for char in value):
        if value not in alpha_values:
            alpha_values.add(value)
            print(value)

Price Each

In [11]:
alpha_values = set()
for value in df['Quantity Ordered']:
    if any(char.isalpha() for char in value):
        if value not in alpha_values:
            alpha_values.add(value)
            print(value)

Quantity Ordered

#### Drop the extra headers that may have been added during concatenation and are not part of the actual data.

In [12]:
## because all the extra header that we want to drop are in the same row every time we can just
## drop one of them to clean the df
df = df[df['Product'] != 'Product']

In [13]:
##test if that work
alpha_values = set()
for value in df['Quantity Ordered']:
    if any(char.isalpha() for char in value):
        if value not in alpha_values:
            alpha_values.add(value)
            print(value)

### `Convert` the columns

In [14]:
# Convert 'Order ID' and 'Quantity Ordered' to integer data type
df[['Order ID', 'Quantity Ordered']] = df[['Order ID', 'Quantity Ordered']].astype('Int64')

# Convert 'Price Each' to float format
df['Price Each'] = df['Price Each'].astype('float')

# Split the 'Order Date' column
df[['Order Date', 'Time']] = df['Order Date'].str.split(' ', n=1, expand=True)
# Convert 'Order Date' column to datetime format with the correct format
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%y')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185950 entries, 0 to 186849
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185950 non-null  Int64
 1   Product           185950 non-null  object
 2   Quantity Ordered  185950 non-null  Int64
 3   Price Each        185950 non-null  float64
 4   Order Date        185950 non-null  datetime64[ns]
 5   Purchase Address  185950 non-null  object
 6   Time              185950 non-null  object
dtypes: Int64(2), datetime64[ns](1), float64(1), object(3)
memory usage: 11.7+ MB

In [16]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Time
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,"917 1st St, Dallas, TX 75001",08:46
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,"682 Chestnut St, Boston, MA 02215",22:30
3,176560,Google Phone,1,600.00,2019-04-12,"669 Spruce St, Los Angeles, CA 90001",14:38
4,176560,Wired Headphones,1,11.99,2019-04-12,"669 Spruce St, Los Angeles, CA 90001",14:38
5,176561,Wired Headphones,1,11.99,2019-04-30,"333 8th St, Los Angeles, CA 90001",09:27

#### split the `Purchase Address` column to have only the city

In [ ]:
def get_city(address):

    return address.split(",")[1].strip(" ")

def get_state(address):

    return address.split(",")[2].split(" ")[1]


df['City'] = df['Purchase Address'].apply(lambda x: f"{get_city(x)}  ({get_state(x)})")

# Display the first few rows of the updated DataFrame
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Time,City
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,"917 1st St, Dallas, TX 75001",08:46,Dallas (TX)
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,"682 Chestnut St, Boston, MA 02215",22:30,Boston (MA)
3,176560,Google Phone,1,600.00,2019-04-12,"669 Spruce St, Los Angeles, CA 90001",14:38,Los Angeles (CA)
4,176560,Wired Headphones,1,11.99,2019-04-12,"669 Spruce St, Los Angeles, CA 90001",14:38,Los Angeles (CA)
5,176561,Wired Headphones,1,11.99,2019-04-30,"333 8th St, Los Angeles, CA 90001",09:27,Los Angeles (CA)

In [18]:
#drop the columns that we dont need for our analysis
df = df.drop(columns=['Purchase Address'])

In [19]:
## create a sales columns to answer the first question
df['Sales'] = df['Price Each']*df['Quantity Ordered']

In [20]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Time,City,Sales
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,08:46,Dallas (TX),23.9
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,22:30,Boston (MA),99.99
3,176560,Google Phone,1,600.00,2019-04-12,14:38,Los Angeles (CA),600.0
4,176560,Wired Headphones,1,11.99,2019-04-12,14:38,Los Angeles (CA),11.99
5,176561,Wired Headphones,1,11.99,2019-04-30,09:27,Los Angeles (CA),11.99

In [21]:
# check how many days we have in 2020
df[df['Order Date'].dt.year == 2020]['Order Date'].unique()

<DatetimeArray>
['2020-01-01 00:00:00']
Length: 1, dtype: datetime64[ns]

In [22]:
# check how many days we have in 2020
df[df['Order Date'].dt.year == 2020]['Order Date'].dt.date.nunique()

1

#### It appears that we only have data for a single day in 2020, and this could potentially distort the dataset. Therefore, I am going to delete it.

In [23]:
# delete 2020 data 
df = df[df['Order Date'].dt.year != 2020]

In [24]:
df.to_csv("data.csv",index=False)